{{- if and .Values.redis.enabled (not (or .Values.externalRedis.url .Values.externalRedis.existingSecret)) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "paperless.fullname" . }}-redis
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
    app.kubernetes.io/component: "redis"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "paperless.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "redis"
  template:
    metadata:
      {{- with .Values.redis.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "paperless.labels" . | nindent 8 }}
        app.kubernetes.io/component: "redis"
        {{- with .Values.redis.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.redis.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-redis
          securityContext:
            {{- toYaml .Values.redis.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          {{- if .Values.paperless.extraEnv }}
          env:
          {{- with .Values.paperless.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
         {{- if or .Values.redis.persistence.enabled .Values.redis.extraVolumeMounts }}
          volumeMounts:
          {{- if .Values.redis.persistence.enabled }}
            - name: {{ include "paperless.fullname" . }}-redis-data
              mountPath: /data
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        securityContext:
          fsGroup: 999
      {{- if .Values.redis.extraVolumes }}
      volumes:
      {{- with .Values.redis.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if or .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "paperless.fullname" . }}-redis-data
      spec:
        accessModes:
          - {{ .Values.redis.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size | quote }}
        {{- if .Values.redis.persistence.storageClass }}
        storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
        {{- end }}
        {{- if .Values.redis.persistence.volumeName }}
        volumeName: {{ .Values.paperless.redis.volumeName | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end -}}
