image:
  repository: quay.io/spacebird-dev/metallb-dyn6
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# --Application loglevel. Can be error,warning,info,debug,trace
loglevel: info

dyn6:
  # --Source of the dynamic IPv6 network that will be injected into MetalLB. Can only be `my-ip` at this point.
  source: my-ip
  subnetOverride:
    # --Whether to enable the subnet override. Both override and prefix_length must be set if this is true.
    enabled: false
    # --Override a portion of the prefix (usually the subnet). This value must be a valid IPv6 address. For example, to set the subnet to :beef: with a /48 dynamic prefix, use: 0:0:0:beef::
    override: "0:0:0:00aa::"
    # --Length of the original network prefix that should be preserved when overriding the subnet with --subnet-override. For example, if you have a /48 prefix and are overriding the subnet with :beef:, set this to 48.
    prefixLength: 56
  # --Time between attempts to refresh the dynamic Prefix and updating the IPAddressPool in seconds
  updateInterval: 60

metallb:
  # --Range of host addresses that MetalLB can use for allocating services. Must be passed as a range of Ipv6-Host-parts, such as ::1000-::1999
  hostRange: ""
  # --Name of the IPAddressPool resource  to manage
  pool: ""
  # --Use this label selector to filter pods when force-deleting MetalLB to refresh its configuration. Only pods that match this selector will be deleted. Only adjust this if your MetalLB instance is installed with a custom label name/instance.
  podsLabelSelector: "app.kubernetes.io/name=metallb,app.kubernetes.io/instance=metallb"

serviceAccount:
  annotations: {}
  name: ""
role:
  annotations:
  name: ""
roleBinding:
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
labels:

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
