apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "metallb-dyn6.roleName" . }}
  labels:
    {{- include "metallb-dyn6.labels" . | nindent 4 }}
  {{- with .Values.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: ["metallb.io"]
  resources: ["ipaddresspools"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete", "deletecollection"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metallb-dyn6.serviceAccountName" . }}
  labels:
    {{- include "metallb-dyn6.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ default (include "metallb-dyn6.fullname" .) .Values.roleBinding.name }}
  labels:
    {{- include "metallb-dyn6.labels" . | nindent 4 }}
  {{- with .Values.roleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "metallb-dyn6.serviceAccountName" . }}
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "metallb-dyn6.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
