apiVersion: v2
appVersion: 0.2.17
description: A utility to automatically generate Ipv4 A DNS records for hosts based
  on existing AAAA records in a DNS zone.
home: https://github.com/spacebird-dev/charts
maintainers:
- email: github@maxhoesel.de
  name: Max Hösel
name: clouddns-nat-helper
sources:
- https://github.com/spacebird-dev/clouddns-nat-helper
type: application
version: 0.3.1
