# -- Set the source to use for determining the A records IPv4 address. Can be either `hostname` or `fixed`
ipv4Source: hostname
hostname:
  # -- Resolve this hostname to get the Ipv4 address to put into a records.
  name: ""
  # -- Optional list of DNS servers to query when resolving `hostname.name`. Will use the applications default servers if not set.
  dnsServers: []
fixed:
  # -- Use this address for all IPv4 records
  address: ""

# -- DNS provider to use. Currently supported: `cloudflare`
provider: cloudflare
cloudflare:
  # -- Cloudflare API Token to authenticate with
  apiToken: ""
  # -- Set to enable proxying for the generated A records in Cloudflare
  proxied: false

registry:
  # -- Unique identifier (tenant) that will be used to identify this instance of nat-helper in DNS records
  tenant: "helm-nat-helper"

# -- Can be any of error,warn,info,debug,trace
loglevel: info
# -- Time to wait between update operations in seconds. 0 results in the app default being used
interval: 0
# -- What A record actions are permitted. createonly: create, upsert: create,update, sync: create,update,delete
policy: sync
# -- Optionally set a TTL for newly created records. Will use the provider default if no specified
ttl: 0

replicaCount: 1

image:
  repository: quay.io/spacebird-dev/clouddns-nat-helper
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
