ipv4Source: hostname # Source of the IPv4 address to set in all A records
hostname: # Configuration for the `hostname` ipv4_source
  name: "" # Resolve this hostname to get the Ipv4 address to put into a records.
  dnsServers: [] # Optional list of DNS servers to query when resolving `hostname.name`. Will use the applications default servers if not set.
fixed: # Configuration for the `fixed` ipv4_source
  address: "" # Ipv4 address to put into all A records

provider: cloudflare # DNS provider to use. Currently supported: `cloudflare`
cloudflare: # Cloudflare provider configuration
  apiToken: "" # Cloudflare API Token to authenticate with
  proxied: false # Set to enable proxying for the generated A records in Cloudflare

registry:
  tenant: "helm-nat-helper" # Unique identifier (tenant) to use for the registry to identify this instance of nat-helper

loglevel: info # Can be any of error,warn,info,debug,trace
interval: 0 # Time to wait between update operations in seconds
policy: sync # What A record actions are permitted. createonly: create, upsert: create,update, sync: create,update,delete
ttl: 0 # Optionally set a TTL for newly created records. Will use the provider default if no specified

replicaCount: 1

image:
  repository: quay.io/maxhoesel/clouddns-nat-helper # Full container repository path
  pullPolicy: IfNotPresent # Optionally set the pull policy
  tag: "" # Optionally specify a custom tag. Defaults to the Chart appVersion

imagePullSecrets: [] #k8s secrets if you are pulling the image from a private registry
nameOverride: ""
fullnameOverride: ""

podAnnotations: {} # Additional annotations for pod resources
podSecurityContext: {} # Additional security context for pod resources
securityContext: {} # Additional security context for this chart

resources: {} # Optional resource limits for resources in this chart
nodeSelector: {}
tolerations: []
affinity: {}
