tag-prefix: "metallb-dyn6-"
include-paths:
  - charts/metallb-dyn6

name-template: 'metallb-dyn6-$RESOLVED_VERSION'
tag-template: 'metallb-dyn6-$RESOLVED_VERSION'
categories:
  - title: 'Major Changes'
    labels:
      - 'pr-major'
  - title: 'Features and Minor Changes'
    labels:
      - 'pr-minor'
  - title: 'Bug Fixes and Patches'
    labels:
      - 'pr-patch'
  - title: 'Other'
    labels:
      - 'docs'

include-labels:
  - pr-major
  - pr-minor
  - pr-patch
  - docs
exclude-contributors:
  - github-actions
  - github-actions[bot]

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'pr-major'
  minor:
    labels:
      - 'pr-minor'
  patch:
    labels:
      - 'pr-patch'
  default: patch

template: |
  ⚠️ **Release Checklist** ⚠️

  Do **NOT** publish this release until you've completed these steps:

  1. Merge any outstanding version update PRs for this chart
  2. Verify that the chart version in Chart.yaml corresponds to this releases version
  3. Ensure that the release notes are correct
  4. Delete this section

  ---

  # Changes

  $CHANGES
