apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paperless.fullname" . }}-config
data:
  {{- if eq .Values.db.type "postgres" }}
  PAPERLESS_DBENGINE: "postgresql"
  {{- else if eq .Values.db.type "mariadb" }}
  PAPERLESS_DBENGINE: "mariadb"
  {{- end }}
  USERMAP_UID: {{ .Values.paperless.podSecurityContext.fsGroup | quote }}
  USERMAP_GID: {{ .Values.paperless.podSecurityContext.fsGroup | quote }}
  PAPERLESS_PORT: "8000"
  PAPERLESS_APP_TITLE: {{ .Values.paperless.appTitle }}
  PAPERLESS_URL: {{ .Values.paperless.url }}
  PAPERLESS_DATA_DIR: {{ .Values.paperless.volumes.data.mountPath }}
  PAPERLESS_MEDIA_DIR: {{ .Values.paperless.volumes.media.mountPath }}
  PAPERLESS_CONSUMPTION_DIR: {{ .Values.paperless.volumes.consumption.mountPath }}
  PAPERLESS_OCR_LANGUAGE: {{ .Values.paperless.ocr.defaultLanguage }}
  PAPERLESS_OCR_LANGUAGES: {{ .Values.paperless.ocr.extraLanguages }}
{{- if .Values.paperless.pathPrefix }}
  PAPERLESS_FORCE_SCRIPT_NAME: {{ .Values.paperless.pathPrefix }}
  PAPERLESS_STATIC_URL: {{ .Values.paperless.pathPrefix }}/static/
{{- end }}
{{- if .Values.externalTika.endpoint }}
  PAPERLESS_TIKA_ENABLED: "true"
  PAPERLESS_TIKA_ENDPOINT: {{ .Values.externalTika.endpoint }}
{{- else if .Values.tika.enabled }}
  PAPERLESS_TIKA_ENABLED: "true"
  PAPERLESS_TIKA_ENDPOINT: {{ printf "http://%s" (include "tika-helm.fullname" .Subcharts.tika) }}:{{ .Values.tika.service.port }}
{{- end }}
{{- if .Values.externalGotenberg.endpoint }}
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: {{ .Values.externalGotenberg.endpoint }}
{{- else if .Values.gotenberg.enabled }}
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: {{ printf "http://%s:%d" (include "gotenberg.fullname" .Subcharts.gotenberg) (int .Values.gotenberg.service.port) }}
{{- end }}
{{- with .Values.paperless.extraConfig }}
  {{- toYaml . | nindent 2 }}
{{- end }}
