{{- if and .Values.paperless.volumes.data.persistence.enabled (not .Values.paperless.volumes.data.existingVolume) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "paperless.fullname" . }}-data
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.paperless.volumes.data.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.paperless.volumes.data.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.paperless.volumes.data.persistence.size | quote }}
  storageClassName: {{ .Values.paperless.volumes.data.persistence.storageClass | quote }}
{{- end }}
