{{- if and .Values.paperless.admin.enabled (or (not .Values.paperless.admin.user.existingSecret) (not .Values.paperless.admin.email.existingSecret) (not .Values.paperless.admin.password.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.fullname" . }}-admin
data:
  {{- if not .Values.paperless.admin.user.existingSecret }}
  PAPERLESS_ADMIN_USER: {{ .Values.paperless.admin.user.name }}
  {{- end }}
  {{- if not .Values.paperless.admin.email.existingSecret }}
  PAPERLESS_ADMIN_MAIL: {{ .Values.paperless.admin.email.address }}
  {{- end }}
  {{- if not .Values.paperless.admin.password.existingSecret }}
  PAPERLESS_ADMIN_PASSWORD: {{ .Values.paperless.admin.password.value }}
  {{- end }}
{{- end -}}
