apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.fullname" . }}-smtp
data:
  {{- if not .Values.paperless.smtp.host.existingSecret }}
  PAPERLESS_EMAIL_HOST: {{ .Values.paperless.smtp.host.name | b64enc }}
  {{- end }}
  {{- if not .Values.paperless.smtp.port.existingSecret }}
  PAPERLESS_EMAIL_PORT: {{ (toString .Values.paperless.smtp.port.value) | b64enc }}
  {{- end }}
  {{- if and (not .Values.paperless.smtp.user.existingSecret) .Values.paperless.smtp.user.name }}
  PAPERLESS_EMAIL_HOST_USER: {{ .Values.paperless.smtp.user.name | b64enc }}
  {{- end }}
  {{- if not .Values.paperless.smtp.from.existingSecret }}
  PAPERLESS_EMAIL_FROM: {{ .Values.paperless.smtp.from.address | b64enc }}
  {{- end }}
  {{- if and (not .Values.paperless.smtp.password.existingSecret) .Values.paperless.smtp.password.value }}
  PAPERLESS_EMAIL_HOST_PASSWORD: {{ .Values.paperless.smtp.password.value | b64enc }}
  {{- end }}
  {{- if eq .Values.paperless.smtp.encryption "ssl" }}
  PAPERLESS_EMAIL_USE_SSL: {{ printf "true" | b64enc }}
  PAPERLESS_EMAIL_USE_TLS: {{ printf "false" | b64enc }}
  {{- else if eq .Values.paperless.smtp.encryption "tls" }}
  PAPERLESS_EMAIL_USE_SSL: {{ printf "false" | b64enc }}
  PAPERLESS_EMAIL_USE_TLS: {{ printf "true" | b64enc }}
  {{- else }}
  PAPERLESS_EMAIL_USE_SSL: {{ printf "false" | b64enc }}
  PAPERLESS_EMAIL_USE_TLS: {{ printf "false" | b64enc }}
  {{- end }}
