{{- if or .Values.db.postgres.enabled .Values.db.mariadb.enabled .Values.db.external.type }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.fullname" . }}-app
data:
  {{- if .Values.redis.external.existingSecret }}
  PAPERLESS_REDIS: {{ .Values.redis.external.url }}
  {{- else }}
  PAPERLESS_REDIS: {{ (printf "redis://:%s@%s-master:%d" .Values.redis.auth.password (include "common.names.fullname" .Subcharts.redis ) (int .Values.redis.master.service.ports.redis)) | b64enc}}
  {{- end }}
  {{- if .Values.db.external.type }}
  PAPERLESS_DBENGINE: {{ .Values.db.external.type | b64enc  }}
  {{- if not .Values.db.external.host.existingSecret }}
  PAPERLESS_DBHOST: {{ .Values.db.external.host.name | b64enc  }}
  {{- end }}
  {{- if not .Values.db.external.port.existingSecret }}
  PAPERLESS_DBPORT: {{ toString .Values.db.external.port.value | b64enc  }}
  {{- end }}
  {{- if not .Values.db.external.database.existingSecret }}
  PAPERLESS_DBNAME: {{ .Values.db.external.database.name | b64enc  }}
  {{- end }}
  {{- if not .Values.db.external.user.existingSecret }}
  PAPERLESS_DBUSER: {{ .Values.db.external.user.name | b64enc  }}
  {{- end }}
  {{- if not .Values.db.external.password.existingSecret }}
  PAPERLESS_DBPASS: {{ .Values.db.external.password.value | b64enc  }}
  {{- end }}
  {{- if .Values.db.external.sslMode }}
  PAPERLESS_DBSSLMODE: {{ .Values.db.external.sslMode | b64enc  }}
  {{- end }}
  {{- if and (not .Values.db.external.sslRootCert.existingSecret) .Values.db.external.sslRootCert.certificate }}
  root-cert: {{ .Values.db.external.sslRootCert.certificate | b64enc  }}
  {{- end }}
  {{- if and (not .Values.db.external.sslClientCert.existingSecret) .Values.db.external.sslClientCert.certificate }}
  client-cert: {{ .Values.db.external.sslClientCert.certificate | b64enc  }}
  {{- end }}
  {{- if and (not .Values.db.external.sslClientKey.existingSecret) .Values.db.external.sslClientKey.key }}
  client-key: {{ .Values.db.external.sslClientKey.key | b64enc  }}
  {{- end }}
  {{- else if .Values.db.mariadb.enabled }}
  PAPERLESS_DBENGINE: "mariadb"
  PAPERLESS_DBHOST: {{ include "mariadb.primary.fullname" .Subcharts.mariadb | b64enc }}
  PAPERLESS_DBPORT: {{ toString .Values.mariadb.primary.service.ports.mysql | b64enc  }}
  PAPERLESS_DBNAME: {{ .Values.mariadb.auth.database | b64enc  }}
  PAPERLESS_DBUSER: {{ .Values.mariadb.auth.username | b64enc  }}
  PAPERLESS_DBPASS: {{ .Values.mariadb.auth.password | b64enc  }}
  {{- else if .Values.db.postgres.enabled }}
  PAPERLESS_DBENGINE: "postgres"
  PAPERLESS_DBHOST: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql | b64enc  }}
  PAPERLESS_DBPORT: {{ toString .Values.postgresql.primary.service.ports.postgresql | b64enc }}
  PAPERLESS_DBNAME: {{ .Values.postgresql.auth.database | b64enc  }}
  PAPERLESS_DBUSER: {{ .Values.postgresql.auth.username | b64enc  }}
  PAPERLESS_DBPASS: {{ .Values.postgresql.auth.password | b64enc  }}
  {{- end}}
{{- end }}
