apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.fullname" . }}-app
data:
  {{- if and .Values.redis.enabled (not .Values.externalRedis.url) }}
  PAPERLESS_REDIS: {{ (printf "redis://%s-redis:%d" (include "paperless.fullname" .) (int .Values.redis.port)) | b64enc}}
  {{- end }}
  {{- if or (eq .Values.db.type "postgres") (eq .Values.db.type "mariadb") }}
  {{- if not .Values.externalDB.host.existingSecret }}
  PAPERLESS_DBHOST: {{ .Values.externalDB.host.name | b64enc  }}
  {{- end }}
  {{- if not .Values.externalDB.port.existingSecret }}
  PAPERLESS_DBPORT: {{ toString .Values.externalDB.port.value | b64enc  }}
  {{- end }}
  {{- if not .Values.externalDB.database.existingSecret }}
  PAPERLESS_DBNAME: {{ .Values.externalDB.database.name | b64enc  }}
  {{- end }}
  {{- if not .Values.externalDB.user.existingSecret }}
  PAPERLESS_DBUSER: {{ .Values.externalDB.user.name | b64enc  }}
  {{- end }}
  {{- if not .Values.externalDB.password.existingSecret }}
  PAPERLESS_DBPASS: {{ .Values.externalDB.password.value | b64enc  }}
  {{- end }}
  {{- if .Values.externalDB.sslMode }}
  PAPERLESS_DBSSLMODE: {{ .Values.externalDB.sslMode | b64enc  }}
  {{- end }}
  {{- if or .Values.externalDB.sslRootCert.certificate .Values.externalDB.sslRootCert.existingSecret }}
  PAPERLESS_DBSSLROOTCERT: {{ printf "/etc/ssl/paperless-root-cert/cert" | b64enc }}
  {{- end }}
  {{- if and (not .Values.externalDB.sslRootCert.existingSecret) .Values.externalDB.sslRootCert.certificate }}
  _root-cert: {{ .Values.externalDB.sslRootCert.certificate | b64enc  }}
  {{- end }}
  {{- if or .Values.externalDB.sslClientCert.certificate .Values.externalDB.sslClientCert.existingSecret }}
  PAPERLESS_DBSSLCERT: {{ printf "/etc/ssl/paperless-client-cert/cert" | b64enc }}
  {{- end }}
  {{- if and (not .Values.externalDB.sslClientCert.existingSecret) .Values.externalDB.sslClientCert.certificate }}
  _client-cert: {{ .Values.externalDB.sslClientCert.certificate | b64enc  }}
  {{- end }}
  {{- if or .Values.externalDB.sslClientKey.key .Values.externalDB.sslClientKey.existingSecret }}
  PAPERLESS_DBSSLKEY: {{ printf "/etc/ssl/paperless-client-key/key" | b64enc }}
  {{- end }}
  {{- if and (not .Values.externalDB.sslClientKey.existingSecret) .Values.externalDB.sslClientKey.key }}
  _client-key: {{ .Values.externalDB.sslClientKey.key | b64enc  }}
  {{- end }}
  {{- end }}
