{{- if not .Values.paperless.secretKey.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.fullname" . }}-key
data:
  PAPERLESS_SECRET_KEY: {{ .Values.paperless.secretKey.value | b64enc }}
{{- end -}}
