paperless:
  url: "https://nonexistent.tld"
  secretKey:
    value: s3fkNVYv8BrZfoPH10UWxEViPhCzf4dP
  admin:
    enabled: true
    password:
      value: kwWTQLSXxF42JEns3wHItXpVfzKPC9Jh

db:
  sqlite:
    enabled: false
  postgres:
    enabled: true

postgresql:
  auth:
    password: qX1GAPE3BBwUquyYurxVT1OpL8ZWHLX7
