{{- if eq .Values.provider "cloudflare" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clouddns-nat-helper.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "clouddns-nat-helper.labels" . | nindent 4  }}
type: Opaque
data:
  cloudflare_api_token: {{ .Values.cloudflare.apiToken | b64enc | quote }}
{{- end -}}
