---
name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
        - name: Check out codebase
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Run pre-commit checks
          uses: pre-commit/action@v3.0.1
