---
name: Prepare a new Chart Release

on:
  workflow_dispatch:
    inputs:
      chart:
        description: Chart that should have a new release
        required: true
        type: choice
        options:
          - metallb-dyn6

jobs:
  prepare-release:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: release-drafter/release-drafter@v5
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter/${{ inputs.chart }}.yml

      - name: Extract version from release name
        run: echo "RELEASE_VERSION=$(echo ${{ steps.drafter.outputs.name }} | sed 's/${{ inputs.chart }}-//')" >> $GITHUB_ENV

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3"

      - name: Update chart version
        working-directory: charts/metallb-dyn6
        run: |
          make version=${{ env.RELEASE_VERSION }} set-chart-version

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ inputs.chart }}: bump version to ${{ env.RELEASE_VERSION }}"
          branch: main
          file_pattern: 'charts/${{ inputs.chart }}/Chart.yaml'
          commit_user_name: GitHub Actions
          commit_user_email: github-actions@users.noreply.github.com
          commit_author: GitHub Actions <github-actions@users.noreply.github.com>
